extends: default

# Ignore helm templates and .terraform provider paths
ignore: |
  .terraform/
  tmp/

rules:
  line-length: disable
  document-start: disable
  comments: disable
  truthy: disable # github workflows uses "on:" a lot, which is a truthy value in yaml
